### ISSUE TITLE
HTTP LS-to-LS - Support Multiple Outputs / High Availability / Loadbalancing

### ISSUE THREAD

**Issue by roaksoax** [logstash-plugins/logstash-integration-logstash#5]
This new logstash to logstash implementation needs to ability to be able to support multiple outputs. This is not only to provide High Availability, but also to be able to increase throughput and so on. 

### Lumberjack Support
The current LS-to-LS with Lumberjack HA mechanism is to support multiple outputs in a Primary/Secondary modes, where Logstash will send data to one of the outputs, and if the communication fails, it will send data to the other available outputs. As such, it does not provide Load Balancing.

### HTTP Input/Output
These plugins don't support HA nor load balancing, and the frequent use case is that users will use a load balancing in between.

### Proposed Solution
The proposed solution is to support multiple outputs in a Round Robin Loadbalacing method, and such, we would support HA and scalability.

### Other Considerations
We could consider adding multiple modes of operation, that supports the following:
 - Loadbalancing - as described above.
 - ~~Primary/Secondaries - as Lumberjack output works today.~~
 
### Tasks:
- [x] replace http-output with https-mixin to directly use http client
- [x] simplify the logic such as no need pending events since plugin uses bulk sending (`json_batch`), @mapping, @retry, default @gzip etc...
- [x] apply load balancing logic by using single shared client

**Comment by yaauie** [comment]
Alternate solution would be to use the HttpClient mixin directly in the Logstash output, which would require absorbing the request-encoding logic into this plugin.

The mixin does _not_ constrain managed connections to a single downstream host, so we could build the URL just-in-time to send payloads through a single shared client.

The biggest "gotcha" applies in any case: a downstream input that is either down or experiencing back-pressure can significantly impact an upstream that has other available downstreams. We tackle this in the Elasticsearch output by selecting the least-concurrently-used downstream for each request, and by evicting downstreams when we encounter connection errors.

The following pseudo-code could provide a reasonable template for a smart-enough round-robin:

~~~ ruby
# Quack interface for use in the Router
DownstreamInfo = Struct.new(:host, :port)


class Router
  include MonitorMixin

  ##
  # Creates a new Router with the provided downstream_infos
  # that ignores errors older than the cooloff period
  # @param downstream_infos [Enumerable<DownstreamInfo>]: a list of downstream hosts
  #                                                       to include in routing
  # @param cooloff [Integer]: The cooloff period in seconds in which downstreams with
  #                           recent errors are deprioritized (default: 60)
  def initialize(downstream_infos, cooloff: 60)
    @hostinfos = downstream_infos.map do |downstream_info|
      DownstreamState.new(downstream_info)
    end
  end

  ##
  # Yields the block with a host/port pair, prioritizing
  # hosts that are less concurrently-used and which have
  # not errored recently.
  # @yieldparam host [String]
  # @yieldparam port [Integer]
  def route(&block)
    selected = synchronize { pick_one.tap(&:increment) }

    yield(selected.host, selected.port)
  rescue
    synchronize { selected.mark_error }
    raise
  ensure
    synchronize { selected.decrement }
  end

  private

  def pick_one
    threshold = Time.now.to_i - cooloff
    @hostinfos.sort_by do |hostinfo|
      [
        [hostinfo.last_error, threshold].max,
        hostinfo.concurrent
      ]
    end.first
  end

  class DownstreamState
    def initialize(hostinfo)
      @host = hostinfo.host
      @port = hostinfo.port

      @concurrent = 0
      @last_error = 0
    end
    attr_reader :host
    attr_reader :port
    attr_reader :concurrent
    attr_reader :last_error

    def increment
      @concurrent += 1
    end

    def decrement
      @concurrent -= 1
    end

    def mark_error
      @last_error = Time.now.to_i
    end
  end
  private_constant :DownstreamState
end
~~~

**Comment by yaauie** [comment]
Interface-wise, I would favor allowing the output to accept _either_ (`host`+`port`) _XOR_ (a list of `host:port` entries to `hosts`):

~~~
output {
  logstash {
    host => "single.host"
    port => 1234
  }
}
~~~

~~~
output {
  logstash {
    hosts => [
      "single.host:1234",
      "another.host:1234"
    ]
  }
}
~~~

**Comment by roaksoax** [comment]
Filed https://github.com/logstash-plugins/logstash-integration-logstash/issues/12 to track as a separate issue.
